    status_response = self._interface.communicate_stop_status()
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 114, in communicate_stop_status
    status_response = self._interface.communicate_network_status()
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 125, in communicate_network_status
    resp = self._communicate_stop_status(status)
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 378, in _communicate_stop_status
    resp = self._communicate_network_status(status)
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 388, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    resp = self._communicate(req, local=True)
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Traceback (most recent call last):
  File "/Users/valenetjong/qiskit/binaryHybridQNN/main.py", line 157, in <module>
    main()
  File "/Users/valenetjong/qiskit/binaryHybridQNN/main.py", line 145, in main
    data = Data(batch_size)
  File "/Users/valenetjong/qiskit/binaryHybridQNN/datasetmaker.py", line 9, in __init__
    self.trainloader = self.trainingdata()
  File "/Users/valenetjong/qiskit/binaryHybridQNN/datasetmaker.py", line 24, in trainingdata
    X_train.targets = X_train.data[idx]
IndexError: index 200 is out of bounds for dimension 0 with size 200