Traceback (most recent call last):
  File "/Users/valenetjong/qiskit/main.py", line 157, in <module>
    main()
  File "/Users/valenetjong/qiskit/main.py", line 145, in main
    data = Data(batch_size, datatype="simulation")
TypeError: __init__() got an unexpected keyword argument 'datatype'